#!/bin/bash

TEST_HDR=$1
TEST_DIR=$2
TEST_DST_DIR="/tmp/test/unit/"
TEST_HEADERS=$(find $TEST_DIR -name *Test.hpp)
INCLUDE_GUARD=TESTS_H_INCLUDED

echo -n "Building precompiled header..."
echo "// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT COMMIT NOR EDIT!" > $TEST_HDR
echo "#ifndef $INCLUDE_GUARD" >> $TEST_HDR
echo "#define $INCLUDE_GUARD" >> $TEST_HDR
echo "" >> $TEST_HDR
echo "#define TEST_DST_DIR \"$TEST_DST_DIR\"" >> $TEST_HDR
echo "" >> $TEST_HDR
echo "/**" >> $TEST_HDR
echo " * Dynamically built list of test headers." >> $TEST_HDR
echo " */" >> $TEST_HDR
echo $TEST_HEADERS | sed 's/Test.hpp/Test.hpp\n/g' | sed 's:^.*\/unit\/\([0-9a-zA-Z_]*Test.hpp\):#include "\1":g' >> $TEST_HDR
echo "" >> $TEST_HDR
echo "#endif // $INCLUDE_GUARD" >> $TEST_HDR
mv $TEST_HDR $TEST_DIR
echo "done."

echo -n "Copying configuration files..."
rm -Rf $TEST_DST_DIR
mkdir -p $TEST_DST_DIR
cp $TEST_DIR/input/database/database.ini $TEST_DST_DIR
cp $TEST_DIR/input/database/database.db $TEST_DST_DIR
cp $TEST_DIR/input/script/script.txt $TEST_DST_DIR
echo "done."

exit 0
